version: '3.7'

services:
  proxy:
    image: nginx:1.19.6-alpine
    container_name: parrot-jira-proxy
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - parrot-frontend-network
      - parrot-api-gateway-network
    depends_on:
      - frontend
      - api-gateway

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parrot-jira-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - parrot-frontend-network
    depends_on:
      - api-gateway

  tasks:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: parrot-jira-tasks
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - REDIS_HOST=redis
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db-tasks
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - parrot-tasks-network
    depends_on:
      - db-tasks
      - redis

  db-tasks:
    image: postgres:13.1-alpine
    container_name: parrot-jira-api-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - parrot-jira-tasks-db:/var/lib/postgresql/data
    networks:
      - parrot-tasks-network

  redis:
    image: redis:6.0.10-alpine
    container_name: parrot-jira-redis
    command: redis-server
    volumes:
      - parrot-jira-redis-data:/var/lib/redis/data
    restart: unless-stopped
    networks:
      - parrot-tasks-network
      - parrot-api-gateway-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: parrot-jira-api-gateway
    environment:
      - NODE_ENV=production
      - PORT=${PORT_API_GATEWAY}
      - REDIS_HOST=redis
      - POSTGRES_USER=${POSTGRES_USER_API_GATEWAY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API_GATEWAY}
      - POSTGRES_HOST=db-api-gateway
      - POSTGRES_DB=${POSTGRES_DB_API_GATEWAY}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - parrot-api-gateway-network
      - parrot-tasks-network
    depends_on:
      - db-api-gateway
      - redis
      - tasks

  db-api-gateway:
    image: postgres:13.1-alpine
    container_name: parrot-jira-api-gateway-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER_API_GATEWAY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_API_GATEWAY}
      - POSTGRES_DB=${POSTGRES_DB_API_GATEWAY}
    volumes:
      - parrot-jira-api-gateway-db:/var/lib/postgresql/data
    networks:
      - parrot-api-gateway-network

networks:
  parrot-tasks-network:
    driver: bridge
  parrot-frontend-network:
    driver: bridge
  parrot-api-gateway-network:
    driver: bridge

volumes:
  parrot-jira-redis-data:
  parrot-jira-tasks-db:
  parrot-jira-api-gateway-db:
